/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiArticleRouteImport } from './routes/api/article'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiOpinionsRouteImport } from './routes/api/opinions'
import { Route as ApiShareImageRouteImport } from './routes/api/share-image'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticleRoute = ApiArticleRouteImport.update({
  id: '/api/article',
  path: '/api/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpinionsRoute = ApiOpinionsRouteImport.update({
  id: '/api/opinions',
  path: '/api/opinions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareImageRoute = ApiShareImageRouteImport.update({
  id: '/api/share-image',
  path: '/api/share-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/article': typeof ApiArticleRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/opinions': typeof ApiOpinionsRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/article': typeof ApiArticleRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/opinions': typeof ApiOpinionsRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/article': typeof ApiArticleRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/opinions': typeof ApiOpinionsRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/article'
    | '/api/feed'
    | '/api/opinions'
    | '/api/share-image'
    | '/api/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/article'
    | '/api/feed'
    | '/api/opinions'
    | '/api/share-image'
    | '/api/weather'
  id:
    | '__root__'
    | '/'
    | '/api/article'
    | '/api/feed'
    | '/api/opinions'
    | '/api/share-image'
    | '/api/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiArticleRoute: typeof ApiArticleRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiOpinionsRoute: typeof ApiOpinionsRoute
  ApiShareImageRoute: typeof ApiShareImageRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/article': {
      id: '/api/article'
      path: '/api/article'
      fullPath: '/api/article'
      preLoaderRoute: typeof ApiArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opinions': {
      id: '/api/opinions'
      path: '/api/opinions'
      fullPath: '/api/opinions'
      preLoaderRoute: typeof ApiOpinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share-image': {
      id: '/api/share-image'
      path: '/api/share-image'
      fullPath: '/api/share-image'
      preLoaderRoute: typeof ApiShareImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiArticleRoute: ApiArticleRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiOpinionsRoute: ApiOpinionsRoute,
  ApiShareImageRoute: ApiShareImageRoute,
  ApiWeatherRoute: ApiWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
